name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install tools
      run: |
        go install github.com/go-task/task/v3/cmd/task@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@master

    - name: Checkout code
      uses: actions/checkout@master    

    - name: Verify dependencies
      run: go mod verify

    - name: Lint
      run: task lint

    - name: Test
      run: task test

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
